# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 首页
    url: /
    weight: 1
  - name: 随笔
    url: blog/
    weight: 5
  - name: 文档
    url: docs/
    weight: 10
  - name: 标签
    url: tags/
    weight: 30
  - name: 工具
    url: uses/
    weight: 20
  - name: 关于
    url: about/
    weight: 40
