# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 首页
    url: /
    weight: 1
  - name: 文章
    url: docs/
    weight: 10
  - name: 话题
    url: tags/
    weight: 20
  - name: 工具
    url: uses/
    weight: 30
  - name: 关于
    url: about/
    weight: 40
